# **************************************************************************** #
#                                                                              #
#                                                         ::::::::             #
#    Makefile                                           :+:    :+:             #
#                                                      +:+                     #
#    By: niki <niki@student.codam.nl>                 +#+                      #
#                                                    +#+                       #
#    Created: 2020/07/26 18:57:16 by niki          #+#    #+#                  #
#    Updated: 2020/07/26 19:06:29 by niki          ########   odam.nl          #
#                                                                              #
# **************************************************************************** #

NAME = megaphone

SRC = megaphone.cpp

FLAGS = -Wall -Werror -Wextra

all: $(NAME)

$(NAME): 
	clang++ $(FLAGS) $(SRC)

clean:
	rm -f $(NAME)

fclean: clean

re: fclean $(NAME)

